### ISSUE TITLE
Incompatibility issue with RFTools Dimensions

### ISSUE THREAD

**Issue by sharkck** [Glitchfiend/TerraBlender#111]
### What's the issue you encountered?

As reported back on December 14th last year (https://github.com/McJtyMods/RFToolsDimensions/issues/424) Terrablender is causing issues with RFTools Dimensions.  The 136 beta partially fixes it.  Is there an ETA on when this can be resolved?

In RFTools Dimensions, due to Terrablender, the platforms do not spawn and neither does the dimlet huts.  In addition, when trying to create worlds with specific biomes/terrain (ie: void world), the world generates with random crazy features instead of what you built it with.

### How can the issue be reproduced?

Create a world with non-default biomes/terrain.

### Logs

N/A

### Mod Version

TerraBlender-forge-1.19.2-2.0.1.136

**Comment by sharkck** [comment]
In case it is asked, I'm using the following up-to-date RF Tools versions:
![image](https://user-images.githubusercontent.com/960552/218861701-2155b01e-68bc-44ec-9f22-4b38fe1d30c2.png)

**Comment by Adubbz** [comment]
As mentioned on Discord, this would likely be because modded biomes aren’t being added to their possible biomes list in their biome source. TerraBlender is able to do this itself with Vanilla’s biome source, but not theirs given they are created at runtime. Accordingly, this will need to be handled on their side.

**Comment by Adubbz** [comment]
With the above in mind, I’m going to close this, since I don’t believe it can be resolved on TerraBlender’s side.
