### ISSUE TITLE
Grass Blocks generating under the surface Grass Blocks

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/TerraBlender#125]
### What's the issue you encountered?

Hello,

I've recently started learning developing and Terrablender has been great of a help for me, everything else works fine but I've noticed that when selecting Grass blocks in the SurfaceRules, that it generates both on the surface and also it generates there where dirt is supposed to be. Apologies if this is not an issue or just a really simple fix, but I've tried for hours trying to fix this issue with no avail (With no fix found online either), as I'm still a begginer dev.
![screenshot](https://github.com/Glitchfiend/TerraBlender/assets/114415094/e3d4d923-0a8a-4894-9049-6a393b8a323e)

### How can the issue be reproduced?

Follow the example provided in the [repository](https://github.com/Glitchfiend/TerraBlender/tree/TB-1.19.4-2.2.x/Example/Forge)

### Mod Version

1.19.4-2.2.0.168 (Forge)

**Comment by Adubbz** [comment]
This isn't a TerraBlender bug. I would strongly suggest looking at Mojang's surface rules for a reference on how to use them effectively. The examples are only really meant as a representation of what using TerraBlender's API would look like, rather than a guide to adding decent-looking biomes. I have formatted/named Mojang's surface rules [here](https://github.com/Glitchfiend/TerraBlender/blob/TB-1.20-3.x.x/Common/src/main/java/terrablender/worldgen/TBSurfaceRuleData.java) which may be of use.

**Comment by ghost** [comment]
Ah I see, thanks for your reply, and thanks for the references!
