### ISSUE TITLE
Terrablender removal crashes and corrupts world

### ISSUE THREAD

**Issue by RichPrune** [Glitchfiend/TerraBlender#131]
### What's the issue you encountered?

So, terrablender is supposed to mix together all the modded biomes in with terralith biomes, cool. But then you actually play it. It is one of the most incompatible mods I have ever seen. So far, it has made it so the glimmering weald spawns on the surface when enabled, structures spawn horrible and worldgen sharp and squarey, and so many more. It doesn't even work with half the modded biomes I care about, like glowstone canyon. But thats not why I'm here today.

       I'm here because it has the audacity to corrupt and crash worlds once you remove it, if it wasn't horrible enough. Removing terrablender makes the world crash on load,
the chunks r all permanently fucked up, and I have no backups. But the world isn't what I care about. I am making a public modpack that is already played by a lot of people, so now i face the dilemma: do i prevent my friends from updating their worlds to the biggest update yet, or do I not remove this and let it continue wreaking havoc on all our worlds? It's been responsible for a LOT of headache. Please fix it so i can remove it without corrupting.
[crash-2023-09-19_19.49.00-server.txt](https://github.com/Glitchfiend/TerraBlender/files/12667347/crash-2023-09-19_19.49.00-server.txt)

### How can the issue be reproduced?

heres exactly what happened:
Download my modpack.
Install terrablender(it seems to work at first)
load a world and load chunks.
Uninstall terrablender
Open world, crash. 

### Logs

above

### Mod Version

1.19.2 forge

**Comment by RichPrune** [comment]
update: no mod in my pack depends on terrablender. this mod was definitely the issue.

**Comment by Adubbz** [comment]
As stated on Discord, the crash linked is caused by Supplementaries, not TerraBlender. Chunk issues are caused by the world seed being reset, which also not a TerraBlender issue. Rather, that occurs in general when world generation or structure mods are removed.

**Comment by RichPrune** [comment]
no worldgen or structure mods were removed.

**Comment by RichPrune** [comment]
the "supplementaries crash" was a block from the mod that got displaced by your mod removal. Supplementaries, in my literal YEAR of constantly using it in every single pack, has never caused a single issue for me until you got butthurt about your mod being broken. Cool story bro

**Comment by Adubbz** [comment]
By adding TerraBlender you’ve enabled the TerraBlender integration with whatever mods installed that support it. Those mods do not necessarily have to have a hard dependency on TerraBlender. You’ve then removed TerraBlender, disabling that integration and your world seed has reset in doing so. Thus, you have in fact effectively removed world generation mods. As you have been advised before, you should always make a backup before doing this as breakage is *expected behaviour*.

Myself and others have tried to work with you on this on Discord but you’ve shown a significant unwillingness to listen or accept any explanations given to you (not to mention your absurd claims that this is a Trojan horse when literally anyone can inspect the source and see for themselves that it isn’t).
