### ISSUE TITLE
Server crash on startup - java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList

### ISSUE THREAD

**Issue by ccryx** [Glitchfiend/TerraBlender#132]
### What's the issue you encountered?

Using forge 1.20.2-48.0.30 and only the TerraBlender mod, I get a crash on startup.

### How can the issue be reproduced?

- Set up a fresh forge server with version 1.20.2-48.0.30
- Start once to generate the mod folder etc. and shut down
- Put the TerraBlender-forge-1.20.2-3.0.0.170.jar in the mod folder and restart the server

What didn't help:
- Deleting the config directory
- Deleting the world (since it was generated before adding the mod)

### Logs

https://gist.github.com/ccryx/7605b24247d66dbdcbbf9f525b499b04

### Mod Version

3.0.0.170

### Additional information

Since com.google.common.collect.ImmutableList is part of guava I took a look in the libraries directory but AFAICT guava is included and should be loaded. To see if it's a general bug with forge, I tried a random other mod (though I guess if the mod isn't using the class that doesn't really mean anything).

From the log you can tell that I've set up the server using the PufferFish panel but the behavior is the same when setting up the server manually.

**Comment by Sparrow231129** [comment]
Same thing happened to me. Subtle differences, since I'm a different user, with a different experience level, playing on a different computer, not using shaders, resource files, fabric, or the basic settings of the original writer. The only thing the same between him and I is the Java platform of Minecraft, version 1.20.2

The crash occurs approximately 1/3 to 1/2 the way through the initial loading screen as forge "forges" the new mod(s) into the Minecraft start screen. Error code is "1" and you do not get a button on the crash screen to view the log file.

**Comment by Adubbz** [comment]
This issue has actually already been fixed, but it appears that Forge has taken down their Jenkins so new builds of TerraBlender are no longer being produced automatically. I'll have to look into transitioning to GitHub actions to address this. In the meantime you may be able to workaround this by downgrading to an earlier version of Forge

**Comment by ronofthedead07** [comment]
I'm having this same issue as well. FYI I tried downgrading Forge to 48.0.22 and it did not help.

**Comment by Adubbz** [comment]
A new build has been released with the fix for this.
