### ISSUE TITLE
Terralith + Terrablender + Any-structure-mod = no structures

### ISSUE THREAD

**Issue by Panderine** [Glitchfiend/TerraBlender#37]
### What's the issue you encountered?

This only happens when using both terralith AND Terrablender for example with AE2. Meteorites won't spawn. Also using just any of the 2 would make all structure mods spawn. 

### How can the issue be reproduced?

install the 3 mentioned mods and /locate ae2:meteorite. Won't find any.

### Mod Version

1.1.0.73

### Additional information

MC 1.18.1
Fabric loader.

**Comment by itsdinkd** [comment]
Meteorites do not spawn with Terralith, regardless of Terrablender.

**Comment by Panderine** [comment]
It does for me. Only when combining these 2 mods It won´t. I need to test with previous FRAPI version. I think latest version could be the issue.

**Comment by Panderine** [comment]
I did 3 tests with this mod versions:

- ae2 10.1.0-beta1
- Fabric API 0.46.4+1.18
- SeedFix + Terralith 1.0.0
- TerraBlender 1.1.0.73

The results:
- All the mods = NO meteorites
-  Terralith + AE2 = meteorites
-  Terrablender + AE2 = meteorites

So there must be something having both that doesn't work for AE2 i guess?. I'll try reporting this to AE2 as well.

**Comment by itsdinkd** [comment]
Weird.... Terralith plus Ae2 doesn't give me any meteorites. With or
without terrablender.

**Comment by itsdinkd** [comment]
> I did 3 tests with this mod versions:
> 
> * ae2 10.1.0-beta1
> * Fabric API 0.46.4+1.18
> * SeedFix + Terralith 1.0.0
> * TerraBlender 1.1.0.73
> 
> The results:
> 
> * All the mods = NO meteorites
> * Terralith + AE2 = meteorites
> * Terrablender + AE2 = meteorites
> 
> So there must be something having both that doesn't work for AE2 i guess?. I'll try reporting this to AE2 as well.

Damn I must have another mod stopping meteorites then. Great.

**Comment by ScoobyVI** [comment]
Just to add another example - I'm using 1.18.1 with Terralith 2.0 and Bosses of Mass Destruction (which adds several boss structures). After installing BYG Refabricated and TerraBlender, modded structures no longer generate

**Comment by JDtheHutt** [comment]
I can confirm this.  I setup a new modlist and noticed the same, that structures from mods were absent. I just removed the couple of extra small overworld biome changing mods I had, as well as Terrablender, and the structures all appeared correctly when I regenerated the world. Adding it back in again stops them showing up.

**Comment by itsdinkd** [comment]
I found that Repurposed Structures had an update that broke modded
structure spawn. Not sure if you use this mod, but they also fixed this in
newer versions.

**Comment by ScoobyVI** [comment]
@itsdinkd Thanks for the info. Repurposed Structures is on my list to test, but I haven't yet installed it so my issue must be something different

**Comment by JDtheHutt** [comment]
I posted some comments on [https://github.com/Glitchfiend/TerraBlender/issues/22](url) but they are more appropriate here as that relates to the crash issue.  Will add my information below so that people don't have to jump to an unrelated ticket.

With Terralith and Terrablender: Better End and Better Nether biomes and content loaded as expected and I could locate and tp to their modded biomes and structures with no issue. Other mods that also add structures to the End and Nether also were able to generate in both dimensions with no issue. I tried Better Nether with Amplified Nether too, and that worked fine as well. I also tried without Better End and Better Nether, and in both vanilla dimensions other modded structures again spawned without issue.

However, in the Overworld no modded structures are appearing (tried Stoneholm, Repurposed Structures, Towers of the Wild and others), with one odd exception. The Graveyard mod is able to spawn its structures in the Overworld. I tried both the Graveyard version with its own biomes, as well as without its own biomes, and with both it has been the only mod able to spawn its structures into the Overworld when Terrablender and Terralith are used.

I also tried some mods that spawn additions to existing structure generation. Bountiful and Waystones are able to add a Bounty board structure and Waystone structure to vanilla villages just fine. So it seems that modifications to vanilla content already generating works, just not entire new mod structures standing alone, except for that odd Graveyard matter.

In my other tests, even with hundreds of mods and dozens of datapacks combined, everything spawns as expected in the Overworld so long as Terrablender is not used with Terralith. The moment Terrablender is involved, all Overworld structures added by mods stop spawning but End and Nether are fine even if those two dimensions are modded for their worldgen.

There was concern that Repurposed Structures may be an issue.  However, I am on latest for Repurposed Structures, and in the tests I tried both with a bunch of structure mods all together, one at a time, and a couple at a time, so see if it made any difference. Repurposed Structures had no effect on anything, it was only when switching Terrablender in and out that things changed.

**Comment by Sunconure11** [comment]
Any new revelations on this?

**Comment by badgermemelord** [comment]
Any news?

**Comment by Adubbz** [comment]
This should be fixed in 1.18.2.

**Comment by Master-Nox** [comment]
Any chance we could get this fix backported to 1.18.1? I know its a difficult ask but I figured I might as well ask.

**Comment by Adubbz** [comment]
That's not possible without breaking compatibility with every single mod that uses TerraBlender on 1.18.1. This problem was fixed as a result of fundamental changes to how TerraBlender works which are incompatible with TerraBlender's old API.

**Comment by Master-Nox** [comment]
> That's not possible without breaking compatibility with every single mod that uses TerraBlender on 1.18.1. This problem was fixed as a result of fundamental changes to how TerraBlender works which are incompatible with TerraBlender's old API.

Fair enough, thanks for the quick response.

**Comment by itsdinkd** [comment]
Won't be able to use this in my pack until the major mods port to .2. Same with the other major modpacks.  However, it's great that you fixed
this, thank you. Looking forward to using it
