### ISSUE TITLE
Frequent World Gen Soft-Freeze & World Corruption

### ISSUE THREAD

**Issue by VaelophisNyx** [Glitchfiend/TerraBlender#64]
### What's the issue you encountered?

When exploring the world will randomly cease world gen, and TPS will basically hit 0 sometimes. Not sure what the root cause is but I suspect its either this or Terralith?  particularly `[21:58:13] [Server thread/ERROR]: Element Reference{ResourceKey[minecraft:worldgen/processor_list / minecraft:empty]=ProcessorList[[]]} is not valid in current registry set ` is of note, I think

### How can the issue be reproduced?

Entirely unsure of the cause or how to make it reproducable

### Logs

[latest.log](https://github.com/Glitchfiend/TerraBlender/files/8527041/latest.log)

### Mod Version

1.1.0.99

**Comment by VaelophisNyx** [comment]
Further clarification, the freeze doesn't stop the player moving around. Additionally some chunks will generate but not render.

**Comment by VaelophisNyx** [comment]
Another possible culprit could be Sodium?

**Comment by paradoxuum** [comment]
I had a similar error (though the message was much larger) on Forge 1.18.2 - this appeared every time the world was saved; i.e. whenever the world was auto-saved, and also when using the `/save-all` command. It likely isn't caused by TerraBlender (on Forge) as the error doesn't appear when testing with BYG.

After some testing, I found that this issue was caused by a mod called Blue Skies (this has since been fixed).
I would recommend removing some mods (try structure ones first) to try and figure out what the issue could be caused by.

**Comment by Lozf** [comment]
So I had the same problem- chunks generating but not rendering.  I solved this issue by stepping back to terrablender 1.18.2-1.1.0.99 and oh the biomes youll go 1.18.2-1.4-RC-17.  It was not fixed until I stepped _both_ mods back to these versions.  This happened during world creation.  I had been using the latest version of both mods

**Comment by aAndrew3030** [comment]
I just started experiencing this issue after installing Rubidium (a sodium port). I suspect it is the culprit, due to the fact that the chunk generates properly, but the textures won't render?

**Comment by Jukabofy** [comment]
I'm having the same problems, Itought it was solved in the last versions,still happening


> I just started experiencing this issue after installing Rubidium (a sodium port). I suspect it is the culprit, due to the fact that the chunk generates properly, but the textures won't render?

Yes, probably, I have the same mod, who else s having this problem using Rubidium?

**Comment by aAndrew3030** [comment]
My issue ended being unrelated to Terrablender or Rubidium

**Comment by Jukabofy** [comment]
> My issue ended being unrelated to Terrablender or Rubidium

@aAndrew3030 what was that?

**Comment by JKaiya** [comment]
I just discovered the same problem. I did not notice this before when I used my old mods 2-3 weeks ago. I reverted terablender and Oh the Biome's You'll go, however the world corruption persists. One example is placing book cases, they are invisible, and they do not consume a bookshelf in survival. They reapear once you break a block. If you break the visible or invisibile bookshelf you can get the books from them. I do not remember having this problem in the older versions of forge, however, I must use the .63 version due to optifine as I prioritize shaders.

Another horrible bug I noticed was once you delete these two mods, the end and nether break, and you must create a brand new world, and transfer (replace) all the files with your old wolrd files other than the 2 data folders. Make sure to put all your items in a chest too.

In Case you guys have a chest bug, this is due to terralith, and not terrablender / Oh the Biomes you'll Go.
