### ISSUE TITLE
Mod cannot be downloaded via third party launchers

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/TerraBlender#72]
### What's the issue you encountered?

Mod cannot be downloaded from third party launchers

### How can the issue be reproduced?

Attempt to download the mod on any third party launcher from Curse

### Logs

N/A

### Mod Version

N/A

### Additional information

Just as the title says.

To fix this, go to the CurseForge page, and go to license, and select the appropriate option.

**Comment by Adubbz** [comment]
This is not a bug. This option has been disabled as Curse has made it so we do not receive any form of support when the mod is downloaded via third party launchers. The options are to switch to the Curse launcher (or pressure them to support Linux), or get third party launchers to adapt to Curse’s new system.

**Comment by copygirl** [comment]
Modded Minecraft is not just CurseForge. A healthy, growing, competitive modding ecosystem should allow for third party services, launchers and auto-updating modpacks such as [packwiz](https://github.com/packwiz/packwiz). Locking in your mod to just the CurseForge launcher, being a platform that has lacked very much needed updates (such as a useful search and filtering system just to find compatible mods) for years, and which locks out all non-Windows user, is not nice. It hurts regular users using perfectly fine third-party services, forcing them to manually download mods and place them in the modpack's mods folder. I thought this was an issue of the past.

If by "support" you are talking about Curse's reward points, I'm willing to donate 20€ to the project to offset the loss of points that may occur due to third-party downloads. (Though I doubt they would have noticeable impact.)

Please reconsider.

**Comment by blackd** [comment]
> This is not a bug. This option has been disabled as Curse has made it so we do not receive any form of support when the mod is downloaded via third party launchers. The options are to switch to the Curse launcher (or pressure them to support Linux), or get third party launchers to adapt to Curse’s new system.

tbh I don't think the reward system has anything to do with that. I have a mod and I have allowed it to be downloaded by third party launchers. So far I have 15% increase of points since the change have taken effect. 
Also If I was implementing the award system I would grant points only for ads shown alongside the mod in question. So that would mean no points for third party launcher even with the old rest api. 

Of course my mod is very small with just 1.3mil downloads. May be bigger devs get different deal with OverWolf. But I think the whole idea is to scare the devs so OverWolf to collect more analytics data that they can sell. Eventually they may show more ads too but with how most of the launchers implement the download currently I doubt it.

**Comment by Sunconure11** [comment]
@copygirl Haven't seen you in ages ever since that one homestuck-themed server... lol

But yeah, do please reconsider. Your mod is relied upon by many other mods, and this mentality could choke many users because the modpack they were playing with suddenly broke as a result of this. Furthermore, not everyone is tech-savvy and is willing to manually update it.

**Comment by LambdAurora** [comment]
>  or get third party launchers to adapt to Curse’s new system.

Except the new system for them to be able to download 3rd-party-disabled mods means either using the CDN link directly or steal CurseForge's official API key. I'm not sure there's much to adapt here.

**Comment by DioEgizio** [comment]
> using the CDN link directly

You can't get it from the API, and if you trying to generate it breaks the ToS. Same for caching the download cdn urls

**Comment by Adubbz** [comment]
Third party downloads have been re-enabled for TerraBlender, though they will remain disabled for all of our other mods.

**Comment by Adubbz** [comment]
Another revision: Third party downloads have now been re-enabled for all our mods for the time being, as we don't think Curse has enough granularity with this option as of right now.
