### ISSUE TITLE
Implement an optional built-in region.

### ISSUE THREAD

**Issue by ExDrill** [Glitchfiend/TerraBlender#82]
### Overview

I've noticed some mods tend to mixin into the OverworldBiomeBuilder class to achieve biome generation. It works well, until a datapack overwrites all of it. I propose a boolean config that adds in a built-in region. I've noticed Terrablender regions can re-implement biomes that use the method explained before.

### Why would this feature be useful?

Not everyone uses Terrablender, or wants to use it for their mods, for any certain reason. With this feature implemented, you could enable the config to register a default region, which would bring back biomes that were once overwritten by a datapack.

**Comment by Adubbz** [comment]
Your suggested implementation doesn't really make sense since a default region already exists for Vanilla. Biomes in this region are exactly what they would be without TerraBlender, datapack or otherwise. TerraBlender doesn't care if a mod injects into OverworldBiomeBuilder or however else they decide to achieve adding their biomes.

Ultimately the "spirit" of your suggestion is to add an option to completely ignore biomes from datapacks and only respect OverworldBiomeBuilder. Whilst that may be possible, it's really just swapping one problem for another which I don't really feel comfortable doing. I would argue that being incompatible with datapacks is a bug with mods deciding to inject into OverworldBiomeBuilder that they need to fix. From a user perspective, if they want to ignore datapacks they should simply remove those datapacks.
