### ISSUE TITLE
World doesn't generate

### ISSUE THREAD

**Issue by Jayerd** [Glitchfiend/TerraBlender#99]
### What's the issue you encountered?

https://crashy.net/NziYGFhZIZ4ubDW0Np5J

### How can the issue be reproduced?

I just made my modpack and tried to make a world then when it starts to load it crashes

### Logs

https://gist.github.com/Jayerd/dc9307c4d1c172b8a71a968418032077

### Mod Version

2.0.1.128

**Comment by Adubbz** [comment]
This is a feature order cycle, which is an issue between one or more biome adding mods. TerraBlender does not add biomes and this is not an issue with TerraBlender.

**Comment by CitiesXL2815** [comment]
okay then ask me this, why does your mod show up in the Crash log, even you say it isn't your mod, when i remove TerraBlender it doesn't crash, so you know what mod is causing it, and pls don't say ars bc other mods adding biomes are having same effect and are all pointing at your mod, even several Dev friends says it's TerraBlender, several mods depend on TerraBlender or requirement, Terrablender may not add Biomes, but it causing other mod adding biome to have crashing issue

**Comment by Adubbz** [comment]
It has never been the case that a mod showing up in a crash log has meant it is necessarily at fault. That concept doesn’t just apply to TerraBlender. TerraBlender is a dependency mod, of course removing it will “””fix””” your issue because suddenly no biomes are being added anymore, so there’s nothing to potentially cause a feature order cycle anymore.
